CREATE TABLE players (
    pl_id INTEGER PRIMARY KEY AUTOINCREMENT,
    pl_name VARCHAR(30) UNIQUE,
    pl_lat DECIMAL(5, 2),
    pl_long DECIMAL(5, 2)
);
CREATE TABLE editions (
    ed_id INTEGER PRIMARY KEY AUTOINCREMENT,
    ed_start_time DATETIME,
    ed_end_time DATETIME,
	ed_cap_n INTEGER,
	ed_cap_s INTEGER,
	ed_vcap_n INTEGER,
	ed_vcap_s INTEGER,
	ed_winner CHAR(1),
    FOREIGN KEY (ed_cap_n) REFERENCES players(pl_id),
    FOREIGN KEY (ed_cap_s) REFERENCES players(pl_id),
    FOREIGN KEY (ed_vcap_n) REFERENCES players(pl_id),
    FOREIGN KEY (ed_vcap_s) REFERENCES players(pl_id),
	CHECK (ed_winner IN ('N', 'S'))
);
CREATE TABLE games (
    g_id INTEGER PRIMARY KEY AUTOINCREMENT,
    g_edition INTEGER,
    g_start_time DATETIME,
    g_end_time DATETIME,
	g_player_n1 INTEGER,
	g_player_n2 INTEGER,
	g_player_s1 INTEGER,
	g_player_s2 INTEGER,
    g_tichu_n1 TEXT,
    g_tichu_n2 TEXT,
    g_tichu_s1 TEXT,
    g_tichu_s2 TEXT,
    g_win_n1 SMALLINT,
    g_win_n2 SMALLINT,
    g_win_s1 SMALLINT,
    g_win_s2 SMALLINT,
    g_ko_n BOOLEAN,
    g_ko_s BOOLEAN,
    g_score_n SMALLINT,
    g_score_s SMALLINT,
    g_tot_score_n SMALLINT,
    g_tot_score_s SMALLINT,
	FOREIGN KEY (g_edition) REFERENCES editions(ed_id),
	FOREIGN KEY (g_player_n1) REFERENCES players(pl_id),
    FOREIGN KEY (g_player_n2) REFERENCES players(pl_id),
    FOREIGN KEY (g_player_s1) REFERENCES players(pl_id),
    FOREIGN KEY (g_player_s2) REFERENCES players(pl_id),
	CHECK (g_tichu_n1 IN ('', 'T+', 'T-', 'GT+', 'GT-')),
	CHECK (g_tichu_n2 IN ('', 'T+', 'T-', 'GT+', 'GT-')),
	CHECK (g_tichu_s1 IN ('', 'T+', 'T-', 'GT+', 'GT-')),
	CHECK (g_tichu_s2 IN ('', 'T+', 'T-', 'GT+', 'GT-')),
	CHECK (g_win_n1 IN (1, 2, 3, 4)),
	CHECK (g_win_n2 IN (1, 2, 3, 4)),
	CHECK (g_win_s1 IN (1, 2, 3, 4)),
	CHECK (g_win_s2 IN (1, 2, 3, 4))
);